In [20]:
import pandas as pd 
import matplotlib.pyplot as plt 

df = pd.read_csv("TV_channel_dataset.csv")

#print(df)

print("First 10 records: ",df.head(10))

First 10 records:     Channel_ID  Channel_Name Language Channel_Category           Popular_Show  \
0      100000        Sun TV    Tamil    Entertainment                  Kayal
1      100001      Vijay TV    Tamil    Entertainment           Super Singer
2      100002  Kalaignar TV    Tamil    Entertainment                Serials
3      100003     Zee Tamil    Tamil    Entertainment           Comedy Shows
4      100004   Star Sports  English           Sports                Cricket
5      100005      Vijay TV    Tamil    Entertainment  Kalakka Povathu Yaaru
6      100006        Sun TV    Tamil    Entertainment           Comedy Shows
7      100007        Raj TV    Tamil    Entertainment       Special Programs
8      100008  Kalaignar TV    Tamil    Entertainment            Movie Shows
9      100009   Star Sports  English           Sports                Cricket

  Show_Category  No_of_Shows Avg_Viewers  Avg_Rating Total_Likes  \
0        Serial           18     1328200         4.8      139254
1         Music           37     7531415         3.4      418114
2        Serial           34     1588719         3.0      154340
3        Comedy            8     6624711         3.7      154409
4        Sports           25     1834834         3.6      236690
5       Reality            8     5037507         NaN      131232
6        Comedy           22    11608941         4.2     1339230
7       Reality            5     7410930         3.7      564570
8        Movies           26     8405345         4.5      914684
9        Sports           31     9656344         3.9     1310226

  Social_Media_Followers YouTube_Views HD_Available  Years_Active  \
0                 879699      80947519          Yes            31
1                6586832      72892761          Yes            20
2                6794133      46798080           No            12
3                 598277      34681210          Yes            18
4                5473089      65168770          Yes            17
5                6242263      63225061           No            26
6                2545397      52731619          Yes            17
7                7999756      48553151          Yes            28
8                6391772      10028469           No            13
9                5129744      42114973          Yes            11

   Subscription_Fee Monthly_Reach
0             180.0       2866591
1             300.0      16857090
2             202.0       2081425
3             125.0      14372542
4              93.0           NaN
5             482.0      17047827
6             145.0      32467309
7             221.0      26323712
8             443.0      16434208
9             203.0      41070047

In [21]:
print("Last 10 records:",df.tail(10))

print("\n Number of rows and columns:",df.shape)

Last 10 records:        Channel_ID Channel_Name Language Channel_Category   Popular_Show  \
60239      160239     Vijay TV    Tamil    Entertainment        Serials
60240      160240       Raj TV    Tamil    Entertainment    Movie Shows
60241      160241       Sun TV    Tamil    Entertainment  Vanathai Pola
60242      160242      Jaya TV    Tamil    Entertainment    Music Shows
60243      160243  Sony Sports  English           Sports       Football
60244      160244          KTV    Tamil           Movies  Comedy Movies
60245      160245     Vijay TV    Tamil    Entertainment   Super Singer
60246      160246          KTV    Tamil           Movies   Tamil Movies
60247      160247     Vijay TV    Tamil    Entertainment      Bigg Boss
60248      160248  Sony Sports  English           Sports       Football

      Show_Category  No_of_Shows Avg_Viewers  Avg_Rating Total_Likes  \
60239        Serial           24     5436217         3.9      222127
60240        Movies           37     1652693         4.5       97895
60241        Serial           18     2280005         4.5      176651
60242         Music           31     3416023         2.9      443920
60243        Sports           36    10004928         2.9     1234370
60244        Movies           16     6868163         4.4      363058
60245         Music           37     9755903         3.6      264195
60246        Movies           30     9644523         4.0     1267227
60247       Reality            8    10455540         4.8      622637
60248        Sports           40     7006275         3.8      178914

      Social_Media_Followers YouTube_Views HD_Available  Years_Active  \
60239                6252029      20204170          Yes            33
60240                3582801      52903242          Yes             4
60241                2503084      12862964          Yes            31
60242                 159552      72475828          Yes            15
60243                4184000       3568883          Yes            12
60244                2304619      93768233          Yes             8
60245              3,320,652      30340824           No            12
60246                 949984      62809727          Yes            33
60247                7973100      87007314          Yes            33
60248                6421598      31419702           No             6

       Subscription_Fee Monthly_Reach
60239             392.0      15684228
60240              80.0       4595930
60241             161.0       3494497
60242             476.0       7636666
60243             435.0      20490846
60244             327.0      18160451
60245             273.0      25700655
60246             462.0      17880020
60247              85.0      21394990
60248             270.0      15016263

 Number of rows and columns: (60249, 16)

In [22]:
print("Columns Names:",df.columns)

Columns Names: Index(['Channel_ID', 'Channel_Name', 'Language', 'Channel_Category',
       'Popular_Show', 'Show_Category', 'No_of_Shows', 'Avg_Viewers',
       'Avg_Rating', 'Total_Likes', 'Social_Media_Followers', 'YouTube_Views',
       'HD_Available', 'Years_Active', 'Subscription_Fee', 'Monthly_Reach'],
      dtype='str')

In [23]:
df.dtypes

Channel_ID                  int64
Channel_Name                  str
Language                      str
Channel_Category              str
Popular_Show                  str
Show_Category                 str
No_of_Shows                 int64
Avg_Viewers                   str
Avg_Rating                float64
Total_Likes                   str
Social_Media_Followers        str
YouTube_Views                 str
HD_Available                  str
Years_Active                int64
Subscription_Fee          float64
Monthly_Reach                 str
dtype: object

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60249 entries, 0 to 60248
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Channel_ID              60249 non-null  int64
 1   Channel_Name            59898 non-null  str
 2   Language                59998 non-null  str
 3   Channel_Category        60249 non-null  str
 4   Popular_Show            59813 non-null  str
 5   Show_Category           60249 non-null  str
 6   No_of_Shows             60249 non-null  int64
 7   Avg_Viewers             59837 non-null  str
 8   Avg_Rating              59952 non-null  float64
 9   Total_Likes             59953 non-null  str
 10  Social_Media_Followers  60016 non-null  str
 11  YouTube_Views           59955 non-null  str
 12  HD_Available            60249 non-null  str
 13  Years_Active            60249 non-null  int64
 14  Subscription_Fee        59976 non-null  float64
 15  Monthly_Reach           59904 non-null  str
dtypes: float64(2), int64(3), str(11)
memory usage: 12.0 MB

In [25]:
print("\n Statictical Summary")
df.describe()

 Statictical Summary

,Channel_ID,No_of_Shows,Avg_Rating,Years_Active,Subscription_Fee
count,60249.000000,60249.000000,59952.000000,60249.000000,59976.000000
mean,130124.000000,22.517104,3.649840,18.992083,274.525077
std,17392.532521,10.384328,0.732191,9.572759,130.654765
min,100000.000000,5.000000,-1.000000,0.000000,-100.000000
25%,115062.000000,14.000000,3.000000,11.000000,161.000000
50%,130124.000000,23.000000,3.600000,19.000000,274.000000
75%,145186.000000,32.000000,4.300000,27.000000,388.000000
max,160248.000000,40.000000,6.500000,75.000000,500.000000

In [26]:
print("Numerical columns:")
print(df.select_dtypes(include = "number").columns)

print("\n Categorical Columns:")
print(df.select_dtypes(include = "object").columns)

Numerical columns:
Index(['Channel_ID', 'No_of_Shows', 'Avg_Rating', 'Years_Active',
       'Subscription_Fee'],
      dtype='str')

 Categorical Columns:
Index(['Channel_Name', 'Language', 'Channel_Category', 'Popular_Show',
       'Show_Category', 'Avg_Viewers', 'Total_Likes', 'Social_Media_Followers',
       'YouTube_Views', 'HD_Available', 'Monthly_Reach'],
      dtype='str')

C:\Users\jishi\AppData\Local\Temp\ipykernel_6688\3879803845.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include = "object").columns)

In [27]:
#Number of unique TV channels 
print("Number of TV channels:",df["Channel_Name"].nunique())

#Display unique channel names 
print("\n Total channel names :",df["Channel_Name"].unique())

#Number od unique show categories
print("\n Number of show categories: ",df["Show_Category"].nunique())

Number of TV channels: 24

 Total channel names : <ArrowStringArray>
[      'Sun TV',     'Vijay TV', 'Kalaignar TV',    'Zee Tamil',
  'Star Sports',       'Raj TV',          'KTV',  'Sony Sports',
 'Colors Tamil',      'Jaya TV',     'ZeeTamil',        'SunTV',
            nan, 'colors tamil', 'COLORS TAMIL',  'ColorsTamil',
     'vijay tv',       'sun tv',    'zee tamil',    'Vijay  TV',
      'unknown',       'SUN TV',      'VijayTV',    'ZEE TAMIL',
     'VIJAY TV']
Length: 25, dtype: str

 Number of show categories:  7

In [28]:
#Data quality checking
print(df.isnull().any().any())

True

In [29]:
#Missing values 
print("Missing Values:", df.isnull().sum())

Missing Values: Channel_ID                  0
Channel_Name              351
Language                  251
Channel_Category            0
Popular_Show              436
Show_Category               0
No_of_Shows                 0
Avg_Viewers               412
Avg_Rating                297
Total_Likes               296
Social_Media_Followers    233
YouTube_Views             294
HD_Available                0
Years_Active                0
Subscription_Fee          273
Monthly_Reach             345
dtype: int64

In [30]:
#the percentage of missing values 
print(df.isnull().mean()*100)

Channel_ID                0.000000
Channel_Name              0.582582
Language                  0.416604
Channel_Category          0.000000
Popular_Show              0.723663
Show_Category             0.000000
No_of_Shows               0.000000
Avg_Viewers               0.683829
Avg_Rating                0.492954
Total_Likes               0.491294
Social_Media_Followers    0.386728
YouTube_Views             0.487975
HD_Available              0.000000
Years_Active              0.000000
Subscription_Fee          0.453120
Monthly_Reach             0.572624
dtype: float64

In [31]:
#Check whether duplicate records exist
print(df.duplicated ().any())
df.duplicated().sum()

False

np.int64(0)

In [32]:
#Check for inconsistent channel names 
print(df["Channel_Name"].value_counts())

Channel_Name
Kalaignar TV    6158
Star Sports     6035
Jaya TV         6004
Sony Sports     5989
KTV             5978
Raj TV          5829
Sun TV          5806
Vijay TV        5784
Colors Tamil    5715
Zee Tamil       5710
COLORS TAMIL      83
SunTV             81
ZeeTamil          80
ZEE TAMIL         80
sun tv            70
ColorsTamil       67
colors tamil      66
SUN TV            66
zee tamil         64
vijay tv          59
VIJAY TV          51
Vijay  TV         44
VijayTV           44
unknown           35
Name: count, dtype: int64

In [33]:
#Duplicate Value Cleaning 
df["Channel_Name"] = df["Channel_Name"].replace({"Sun TV": "SunTV", "Sun TV": "SunTV ", "Sun Tv":"sun tv", "Sun TV":"SUN TV ",
                                                 "Vijay TV":"vijay tv", "Vijay TV":"VIJAY TV", "Vijay TV":"Vijay  TV","Vijay TV":"VijayTV",
                                                 "Colours Tamil":"COLORS TAMIL", "Colours Tamil":"ColorsTamil", "Colours Tamil":"colors tamil",
                                                 "Zee Tamil":"ZeeTamil", "Zee Tamil":"ZEE TAMIL", "Zee Tamil":"zee tamil",
                                                 "Hungama":"unknown" })
print(df['Channel_Name'])

0             SUN TV
1             VijayTV
2        Kalaignar TV
3           zee tamil
4         Star Sports
             ...
60244             KTV
60245         VijayTV
60246             KTV
60247         VijayTV
60248     Sony Sports
Name: Channel_Name, Length: 60249, dtype: str

In [34]:
df[(df["Avg_Rating"]<0)| (df["Avg_Rating"]>5)]

,Channel_ID,Channel_Name,Language,Channel_Category,Popular_Show,Show_Category,No_of_Shows,Avg_Viewers,Avg_Rating,Total_Likes,Social_Media_Followers,YouTube_Views,HD_Available,Years_Active,Subscription_Fee,Monthly_Reach
1592,101592,zee tamil,Tamil,Entertainment,Comedy Shows,Comedy,29,6882038,5.5,224019,2363687,51279669,Yes,22,349.0,26546776
1697,101697,Jaya TV,Tamil,Entertainment,Special Programs,Reality,37,2833611,-1.0,331721,2122607,57912459,Yes,8,222.0,6474134
2660,102660,SUN TV,Tamil,Entertainment,Comedy Shows,Comedy,32,10964174,-1.0,1061476,2244107,9999545,Yes,32,182.0,47934902
2812,102812,Colors Tamil,Tamil,Entertainment,Reality Shows,Reality,12,2113827,-1.0,175120,5175605,59240554,Yes,3,272.0,6812549
3373,103373,Kalaignar TV,Tamil,Entertainment,Special Programs,Reality,12,2324610,-1.0,NaN,173045,41255163,Yes,7,64.0,8650408
4210,104210,Raj TV,Tamil,Entertainment,Special Programs,Reality,15,9844263,6.5,866938,7166648,54504581,Yes,27,328.0,26684189
4635,104635,Sony Sports,English,Sports,Badminton,Sports,31,8929648,6.5,876909,4202024,3458204,Yes,4,230.0,17451145
7220,107220,Jaya TV,Tamil,Entertainment,Movie Shows,Movies,12,5637268,-1.0,358209,2535326,6692772,Yes,20,131.0,21923193
12179,112179,VijayTV,Tamil,Entertainment,Super Singer,Music,32,1332239,-1.0,134443,2651253,96507710,Yes,12,362.0,2230446
12726,112726,Star Sports,English,Sports,Cricket,Sports,5,4707858,5.5,175454,457610,27174075,Yes,13,365.0,11615162
13778,113778,zee tamil,Tamil,Entertainment,Serials,Serial,26,8534110,6.5,1005147,1082257,86023625,Yes,19,427.0,34620204
13793,113793,Kalaignar TV,Tamil,Entertainment,Music Shows,Music,36,1458238,5.5,47224,6429310,68096597,No,25,452.0,3212532
14045,114045,Kalaignar TV,Tamil,Entertainment,Special Programs,Reality,33,6391983,-1.0,306872,3502239,2527398,Yes,27,133.0,24263845
14218,114218,COLORS TAMIL,Tamil,Entertainment,Serials,Serial,37,10611940,5.5,717612,NaN,41448501,Yes,32,473.0,24183327
19210,119210,Star Sports,English,Sports,Cricket,Sports,40,3355671,6.5,333999,1393819,47845899,Yes,27,307.0,7191458
20945,120945,SUN TV,Tamil,Entertainment,Reality Shows,Reality,6,1914871,6.5,247851,5888388,9488785,Yes,29,460.0,2649373
21841,121841,Jaya TV,Tamil,Entertainment,Serials,Serial,24,10114725,6.5,304006,4040902,47247384,Yes,30,285.0,34827324
21992,121992,Jaya TV,Tamil,Entertainment,Special Programs,Reality,11,4469097,5.5,268337,756547,43121593,Yes,21,207.0,5908479
23450,123450,SUN TV,Tamil,Entertainment,Comedy Shows,Comedy,33,6680767,-1.0,875153,519449,23842454,Yes,6,435.0,21391558
26181,126181,Star Sports,English,Sports,Hockey,Sports,20,1130534,6.5,97628,6812452,94281384,Yes,26,194.0,1676637
26376,126376,Colors Tamil,Tamil,Entertainment,Abhirami,Serial,10,2662708,-1.0,154678,1296708,15825222,Yes,23,57.0,6798516
26823,126823,Kalaignar TV,Tamil,Entertainment,Music Shows,Music,39,2091937,-1.0,106870,4164210,18288211,Yes,3,226.0,7943192
27145,127145,VijayTV,Tamil,Entertainment,Kalakka Povathu Yaaru,Reality,30,10990420,-1.0,287787,6491574,33472233,Yes,14,363.0,13778812
32617,132617,NaN,Tamil,Entertainment,Serials,Serial,20,7757377,5.5,750883,5541612,80228029,Yes,5,437.0,29444813
33074,133074,Kalaignar TV,Tamil,Entertainment,Comedy Shows,Comedy,35,2049780,6.5,257568,7039476,58941774,Yes,15,184.0,7494981
33371,133371,Jaya TV,Tamil,Entertainment,Special Programs,Reality,20,NaN,6.5,222145,6733198,56526060,Yes,32,303.0,9033443
34885,134885,Colors Tamil,Tamil,Entertainment,Comedy Shows,Comedy,36,6890731,5.5,852053,1808721,NaN,Yes,13,384.0,27661792
35189,135189,VijayTV,Tamil,Entertainment,Cooku with Comali,Cooking,30,9317305,6.5,332330,1850856,97875335,Yes,5,229.0,18344265
36673,136673,Sony Sports,English,Sports,Badminton,Sports,40,5588311,5.5,578356,4018290,1345593,Yes,7,485.0,16640517
40998,140998,Star Sports,English,Sports,Football,Sports,13,4731354,6.5,342889,3063043,58302556,Yes,25,89.0,11724826
41373,141373,zee tamil,Tamil,Entertainment,Reality Shows,Reality,9,4923386,-1.0,372306,6645363,64176569,Yes,15,375.0,12666869
41596,141596,Sony Sports,English,Sports,Badminton,Sports,14,5474529,5.5,659146,3712566,45073085,Yes,15,95.0,23827350
42996,142996,VijayTV,Tamil,Entertainment,Serials,Serial,21,9878803,6.5,721323,7119377,14621946,Yes,14,125.0,26579432
43123,143123,KTV,Tamil,Movies,Tamil Movies,Movies,14,3625961,5.5,244442,3524311,3960406,No,8,499.0,13050010
44298,144298,Raj TV,Tamil,Entertainment,Music Shows,Music,27,7362619,6.5,1022486,5203058,48633770,Yes,28,458.0,25900246
45029,145029,VijayTV,Tamil,Entertainment,Super Singer,Music,32,5992063,-1.0,277158,4452114,79880520,Yes,10,486.0,21197623
45110,145110,SUN TV,Tamil,Entertainment,Comedy Shows,Comedy,5,5351672,5.5,547358,2851385,83067326,Yes,8,342.0,22365464
45559,145559,Jaya TV,Tamil,Entertainment,Music Shows,Music,31,NaN,-1.0,71601,3932362,44739734,Yes,34,454.0,3877851
45691,145691,Kalaignar TV,Tamil,Entertainment,Serials,Serial,23,1350844,-1.0,145099,6621932,NaN,No,24,165.0,4378582
47447,147447,Colors Tamil,Tamil,Entertainment,Abhirami,Serial,20,1736278,6.5,41975,7758235,16272475,Yes,20,102.0,5624637
47791,147791,Sony Sports,English,Sports,Wrestling,Sports,28,2209913,5.5,284148,3321607,84376489,Yes,23,356.0,9576744
48315,148315,SUN TV,Tamil,Entertainment,Comedy Shows,Comedy,40,1413582,6.5,155292,6495919,27246407,Yes,23,71.0,2586919
50165,150165,Colors Tamil,Tamil,Entertainment,Serials,Serial,14,8223293,5.5,696469,7992009,67527605,Yes,8,399.0,15303374
51488,151488,Raj TV,Tamil,Entertainment,Movie Shows,Movies,33,9688477,-1.0,1213678,3716521,73907289,Yes,17,486.0,14599954
53649,153649,Raj TV,Tamil,Entertainment,Movie Shows,Movies,34,566456,5.5,51071,4957082,94841914,Yes,17,225.0,1288757
54766,154766,Kalaignar TV,Tamil,Entertainment,Serials,Serial,18,8691462,6.5,403068,3470468,88084088,Yes,4,50.0,16507305
57073,157073,KTV,Tamil,Movies,Comedy Movies,Movies,39,7772026,6.5,844142,3207617,89668370,Yes,11,287.0,26142949
59916,159916,VijayTV,Tamil,Entertainment,Serials,Serial,13,4958505,5.5,283348,4609973,85055898,Yes,14,142.0,15615379

In [36]:
df[df['Subscription_Fee']<0]

,Channel_ID,Channel_Name,Language,Channel_Category,Popular_Show,Show_Category,No_of_Shows,Avg_Viewers,Avg_Rating,Total_Likes,Social_Media_Followers,YouTube_Views,HD_Available,Years_Active,Subscription_Fee,Monthly_Reach
3873,103873,Star Sports,English,Sports,Tennis,Sports,9,11359191,4.0,789099,1697218,12887149,Yes,28,-100.0,19851059
7441,107441,Kalaignar TV,Tamil,Entertainment,Movie Shows,Movies,5,8291398,4.0,626150,420196,18854749,Yes,23,-50.0,16791716
9739,109739,VijayTV,Tamil,Entertainment,Serials,Serial,15,10680986,3.3,351554,2663115,23380278,Yes,15,-50.0,32534530
11355,111355,Jaya TV,Tamil,Entertainment,Music Shows,Music,31,7255687,3.0,778801,5333988,50362829,No,18,-100.0,23582452
11512,111512,zee tamil,Tamil,Entertainment,Comedy Shows,Comedy,19,2408096,3.1,130469,2799984,86330062,No,26,-50.0,10362548
11895,111895,Raj TV,Tamil,Entertainment,Serials,Serial,27,10721154,3.7,1297731,3310264,43291314,Yes,25,-100.0,20253111
12765,112765,zee tamil,Tamil,Entertainment,Comedy Shows,Comedy,24,8637410,4.6,1012620,7054564,9555728,Yes,21,-50.0,27102130
13012,113012,Star Sports,English,Sports,Football,Sports,31,2538395,4.6,232198,1819487,14070572,Yes,3,-100.0,9628278
16591,116591,Kalaignar TV,Tamil,Entertainment,Serials,Serial,32,3455146,2.5,350796,4406802,84940019,Yes,30,-100.0,4320144
17179,117179,zee tamil,Tamil,Entertainment,Sembaruthi,Serial,21,2707010,3.0,85691,1283256,98884167,Yes,11,-50.0,8718937
22904,122904,VijayTV,Tamil,Entertainment,Super Singer,Music,12,11453139,3.6,1117960,3192520,18026914,No,4,-100.0,28467857
23477,123477,Raj TV,Tamil,Entertainment,Comedy Shows,Comedy,18,2631810,4.6,169638,4859906,NaN,Yes,12,-100.0,4460585
23582,123582,zee tamil,Tamil,Entertainment,Sa Re Ga Ma Pa,Music,33,11152289,4.0,1130904,7637478,92192527,Yes,26,-50.0,35312536
23673,123673,VijayTV,Tamil,Entertainment,Super Singer,Music,11,5222607,2.9,106709,3804745,10908588,Yes,27,-50.0,7755922
24521,124521,Sony Sports,English,Sports,Tennis,Sports,10,3899246,3.1,160503,"1,581,781",97588288,Yes,18,-100.0,7750206
24586,124586,Jaya TV,Tamil,Entertainment,Music Shows,Music,30,3650356,3.9,225996,7740821,18563731,Yes,24,-100.0,12012621
24825,124825,zee tamil,Tamil,Entertainment,Comedy Shows,Comedy,5,8918443,3.3,765424,6071050,63490559,No,9,-50.0,18130922
25030,125030,VijayTV,Tamil,Entertainment,Cooku with Comali,Cooking,6,NaN,4.9,145891,2375612,46179046,Yes,3,-100.0,3011983
25749,125749,Sony Sports,English,Sports,Wrestling,Sports,40,10965485,4.6,1250011,7589355,58906707,Yes,8,-100.0,17324633
27536,127536,SUN TV,Tamil,Entertainment,Comedy Shows,Comedy,24,3045967,2.9,334962,4262582,24754502,Yes,35,-100.0,10295339
28988,128988,KTV,Tamil,Movies,Comedy Movies,Movies,28,4674309,4.2,122629,5919780,25937303,No,5,-50.0,10338085
29247,129247,KTV,Tamil,Movies,Movie Shows,Movies,18,6010471,3.5,389049,163431,26786618,Yes,13,-50.0,13620139
31863,131863,Sony Sports,English,Sports,Wrestling,Sports,26,7121243,3.8,418468,418992,4812727,Yes,13,-50.0,27882761
31875,131875,Kalaignar TV,Tamil,Entertainment,Special Programs,Reality,27,6601919,2.5,848223,179248,96485325,No,14,-100.0,11988564
32713,132713,Kalaignar TV,Tamil,Entertainment,Music Shows,Music,28,3156289,3.2,167895,3283350,87125342,Yes,17,-100.0,11316353
32817,132817,Jaya TV,Tamil,Entertainment,Movie Shows,Movies,38,10529503,4.1,1415253,3008833,91592746,No,17,-50.0,43889820
33076,133076,Sony Sports,English,Sports,Tennis,Sports,24,9267816,3.3,418506,6102252,86978544,Yes,8,-50.0,13533437
33146,133146,Raj TV,Tamil,Entertainment,Special Programs,Reality,19,3415833,4.2,241509,1369679,59498243,Yes,9,-50.0,12226208
36595,136595,Raj TV,Tamil,Entertainment,Special Programs,Reality,14,9488493,4.4,1248802,4129500,91122923,Yes,4,-100.0,26594745
37763,137763,VijayTV,Tamil,Entertainment,Kalakka Povathu Yaaru,Reality,5,2902182,3.6,236483,4737566,46626605,No,5,-100.0,11666333
40043,140043,KTV,Tamil,Movies,Special Movies,Movies,13,11205239,3.8,753755,3515810,75612119,Yes,28,-100.0,44708905
40662,140662,SUN TV,Tamil,Entertainment,Kayal,Serial,24,8645565,4.3,360837,5610037,29311103,Yes,7,-100.0,14920223
40995,140995,Kalaignar TV,Tamil,Entertainment,Comedy Shows,Comedy,17,5749124,4.1,308083,5548187,52916329,No,15,-50.0,17241832
41768,141768,Sony Sports,English,Sports,Tennis,Sports,9,2734467,4.3,357896,870864,79127241,Yes,14,-50.0,6348964
43258,143258,Jaya TV,Tamil,Entertainment,Special Programs,Reality,31,6274918,2.9,233775,4281065,22040088,Yes,4,-50.0,25811746
43442,143442,VijayTV,Tamil,Entertainment,Serials,Serial,15,864008,3.6,17778,7543404,81567542,No,30,-50.0,3777024
43899,143899,zee tamil,Tamil,Entertainment,Comedy Shows,Comedy,23,6208872,3.0,634201,453006,59766649,No,4,-100.0,14779742
45816,145816,Star Sports,English,Sports,Hockey,Sports,9,8288365,4.7,363315,6367675,88041571,Yes,16,-100.0,20740239
45922,145922,Sony Sports,English,Sports,Wrestling,Sports,36,11647413,2.6,1096435,6226064,37356219,Yes,20,-100.0,22420470
46768,146768,Star Sports,English,Sports,Football,Sports,12,7693275,3.2,630964,6282107,89563267,Yes,28,-100.0,32179646
49040,149040,SUN TV,Tamil,Entertainment,Vanathai Pola,Serial,40,4603396,4.1,575900,2725774,27293165,Yes,29,-100.0,8043296
52688,152688,Raj TV,Tamil,Entertainment,Music Shows,Music,26,9186833,3.5,436961,6715951,15894283,Yes,8,-50.0,38271918
55640,155640,SUN TV,Tamil,Entertainment,Singapenne,Serial,28,2143955,2.6,241521,7027921,45036724,Yes,5,-100.0,7457790
56519,156519,KTV,Tamil,Movies,Action Movies,Movies,11,3459288,4.9,476016,7192477,6510503,Yes,19,-50.0,7419737

In [37]:
print(df[df["Years_Active"] < 0])
print(df["Years_Active"].describe())
print(df["Years_Active"].min(),df["Years_Active"].max())

Empty DataFrame
Columns: [Channel_ID, Channel_Name, Language, Channel_Category, Popular_Show, Show_Category, No_of_Shows, Avg_Viewers, Avg_Rating, Total_Likes, Social_Media_Followers, YouTube_Views, HD_Available, Years_Active, Subscription_Fee, Monthly_Reach]
Index: []
count    60249.000000
mean        18.992083
std          9.572759
min          0.000000
25%         11.000000
50%         19.000000
75%         27.000000
max         75.000000
Name: Years_Active, dtype: float64
0 75

In [38]:
#Convert Avg_Viewers into numeric format
df["Avg_Viewers"] = pd.to_numeric(df["Avg_Viewers"],errors="coerce")

#Check invalid negative values
print((df["Avg_Viewers"] < 0).sum())

0

In [39]:
#Check whether HD_Available contains only yes and no
print(df["HD_Available"].value_counts())
print(df["HD_Available"].isin(["Yes","No"]).all())

HD_Available
Yes    53091
No      7158
Name: count, dtype: int64
True

In [ ]:
#Identify NA, N/A, unknown, and blank values
print(df.isin(["NA", "N/A", "na", "n/a", "unknown", "Unknown",""]).sunm())

In [40]:
#Identity columns where numeric values are stored as text 
print(df.dtypes)

#Specify numeric columns
num_cols = ["Avg_Viewers", "Total_Likes", "Social_Media_Followers", "YouTube_Views", "Monthly_Reach"]

Channel_ID                  int64
Channel_Name                  str
Language                      str
Channel_Category              str
Popular_Show                  str
Show_Category                 str
No_of_Shows                 int64
Avg_Viewers               float64
Avg_Rating                float64
Total_Likes                   str
Social_Media_Followers        str
YouTube_Views                 str
HD_Available                  str
Years_Active                int64
Subscription_Fee          float64
Monthly_Reach                 str
dtype: object

In [41]:
for col in num_cols:df[col] = pd.to_numeric(df[col], errors = "coerce")
for col in num_cols:
    print(col, ":", df[col].dtype)

Avg_Viewers : float64
Total_Likes : float64
Social_Media_Followers : float64
YouTube_Views : float64
Monthly_Reach : float64

In [42]:
#Standardize the channel_name values
df["Channel_Name"] = (df["Channel_Name"].str.strip().str.title().str.replace("Tv","TV"))
print(df["Channel_Name"])

0              Sun TV
1             Vijaytv
2        Kalaignar TV
3           Zee Tamil
4         Star Sports
             ...
60244             Ktv
60245         Vijaytv
60246             Ktv
60247         Vijaytv
60248     Sony Sports
Name: Channel_Name, Length: 60249, dtype: str

In [43]:
#Handling missing values
# Numerical
for col in df.select_dtypes(include="number").columns:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns -> mode
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna(df[col].mode()[0])

print(df.isnull().sum())

Channel_ID                0
Channel_Name              0
Language                  0
Channel_Category          0
Popular_Show              0
Show_Category             0
No_of_Shows               0
Avg_Viewers               0
Avg_Rating                0
Total_Likes               0
Social_Media_Followers    0
YouTube_Views             0
HD_Available              0
Years_Active              0
Subscription_Fee          0
Monthly_Reach             0
dtype: int64

C:\Users\jishi\AppData\Local\Temp\ipykernel_6688\2911709971.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [44]:
# Fill ratings with median

df["Avg_Rating"] = df["Avg_Rating"].fillna(df["Avg_Rating"].median())
print("Avg Rating")
print(df["Avg_Rating"])

df["Subscription_Fee"] = df["Subscription_Fee"].fillna(df["Subscription_Fee"].median())
print("Subscription Fee")
print(df['Subscription_Fee'])

print("\nMInium Subscription Fee")
print(df["Subscription_Fee"].min())

Avg Rating
0        4.8
1        3.4
2        3.0
3        3.7
4        3.6
        ...
60244    4.4
60245    3.6
60246    4.0
60247    4.8
60248    3.8
Name: Avg_Rating, Length: 60249, dtype: float64
Subscription Fee
0        180.0
1        300.0
2        202.0
3        125.0
4         93.0
         ...
60244    327.0
60245    273.0
60246    462.0
60247     85.0
60248    270.0
Name: Subscription_Fee, Length: 60249, dtype: float64

MInium Subscription Fee
-100.0

In [45]:
# Handling unrealistic Years_Active values.
df["Years_Active"] = df["Years_Active"].fillna(df["Years_Active"].median())

print(df["Years_Active"].min())

0

In [46]:
# Fill numerical missing values
for col in df.select_dtypes(include="number").columns:
    df[col]=df[col].fillna(df[col].median())
for col in df.select_dtypes(include="object").columns:
    df[col]=df[col].fillna(df[col].mode()[0])
print(df.isnull().sum())

Channel_ID                0
Channel_Name              0
Language                  0
Channel_Category          0
Popular_Show              0
Show_Category             0
No_of_Shows               0
Avg_Viewers               0
Avg_Rating                0
Total_Likes               0
Social_Media_Followers    0
YouTube_Views             0
HD_Available              0
Years_Active              0
Subscription_Fee          0
Monthly_Reach             0
dtype: int64

C:\Users\jishi\AppData\Local\Temp\ipykernel_6688\1713354510.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns: